# Generated by Django 4.0.4 on 2022-09-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('keyss', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='datarow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('phones', 'PHONES'), ('helmets', 'HELMETS'), ('toys', 'TOYS'), ('clothing', 'CLOTHING'), ('fridge', 'FRIDGE')], max_length=20)),
                ('size', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('price', models.CharField(max_length=12)),
                ('category', models.CharField(choices=[('phones', 'PHONES'), ('helmets', 'HELMETS'), ('toys', 'TOYS'), ('clothing', 'CLOTHING'), ('fridge', 'FRIDGE')], max_length=20)),
                ('size', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=10)),
                ('lastname', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='person1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=8)),
                ('image', models.ImageField(upload_to='')),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Userper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.CharField(max_length=12)),
                ('password1', models.CharField(max_length=200)),
                ('password2', models.CharField(max_length=200)),
            ],
        ),
    ]
